### ISSUE TITLE
Faster navigation

### ISSUE THREAD

**Issue by pepastach** [IngoMeyer441/simple-term-menu#7]
Hi,

I'm a big fan of simple-term-menu. It finally made me rewrite dozens of shell script to pure python and make it easy to use for the whole team :)
However, as the number of items grow, it would be great to navigate/filter the items by typing sub-string. Either prefix or a general substring (case insensitive).

Imagine menu like this:
```
> Test everything
  Test project_a
  Test project_b
  Test project_c
  Test project_d
  Show outdated dependencies
  Update dependencies
  Cleanup build residues
  ML model training
  ML model evaluation
```

It would be great to type **clean** and have the `Cleanup build residues` item either or filtered everything else out.
What do you think?

Thanks!

**Comment by IngoHeimbach** [comment]
Hey,
I am glad to read that my project is useful for others. :slightly_smiling_face: 
I think that is a good idea. I use [fzf](https://github.com/junegunn/fzf) in lots of my interactive terminal tools which does a quite similar job and works very well. I can try to add an fzf-style filter mode to simple-term-menu.
Since `j` and `k` can be used for menu selection navigation, I think it would be best to activate the filter mode with a special key like `/` (because many terminal tools use `/` for their search mode). Would that be ok?

**Comment by pepastach** [comment]
Yeah, that's a good point with j/k navigation. `/`-activated search mode would be great and feel familiar.

**Comment by Seluj78** [comment]
Hey ! Any updates on this ? I'm working on integrating `simple-term-menu` in https://github.com/seluj78/potodo and that would do me wonders !

**Comment by IngoMeyer441** [comment]
I have already started to implement a search feature, but couldn't finish it before my holidays. I think the feature will be available in about two weeks.

**Comment by Seluj78** [comment]
That's amazing ! Thanks 🙌

**Comment by IngoMeyer441** [comment]
Hey guys,
[v0.7.0](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v0.7.0) is out with a [search feature](https://github.com/IngoMeyer441/simple-term-menu#searching). The search mode can be activated on `/` by default. For @pepastach it has also an alternative mode in which the search is activated on every letter key.
Could you please test the new version and post some feedback? I had to restructure quite lot of the code and probably there are still some small bugs...

**Comment by Seluj78** [comment]
It's amazing ! Thank you so much for the work !

Here's an asciinema cast of me trying it out

https://asciinema.org/a/2zr1jJWt9Vr2yw8cIqPY3c2mH

As you can see, I had some trouble because I'm still missing a back and exit button 😉 

It's working as intended, but the user can press twice the `/` key which migth throw him off.\

Also, as you can see, the `bisect` file wasn't found...

If you want to try and reproduce, I am on the branch https://github.com/Seluj78/Potodo/tree/feature/interactive-menu where you can simply install the requirements, install the package in dev mode with `pip install -e .` and then test the command `potodo -i` (-i for interactive.)

You might want to also clone the French python doc repository located at https://github.com/python/python-docs-fr and pass the `-p` path parametter !

**Comment by IngoMeyer441** [comment]
Thanks for testing!
Catching a second `/` should be an easy one. But I have no idea why `bisect.po` is not found... I can have a look at this later.

**Comment by IngoMeyer441** [comment]
I think I found the issue. I used a wrong variable for some viewport calulations... It works for me now. Could you test again, @Seluj78?

**Comment by IngoMeyer441** [comment]
I have already tagged a bug fix release v0.7.1

**Comment by Seluj78** [comment]
It works perfectly ! 
Quick idea: Add a `press / to search` prompt at the top or bottom ?

**Comment by IngoMeyer441** [comment]
Pass `show_search_hint=True` to the `TerminalMenu` constructor to show a search hint at the bottom / search line. See also #8.

**Comment by Seluj78** [comment]
Works perfectly ! Thank you ! 🙌

**Comment by IngoMeyer441** [comment]
@pepastach Does the search feature also work well for you?

**Comment by Seluj78** [comment]
Yes it does now, Sorry I thought I had mentionned it!
